data:
  - name: Sly 2, Basic Blending, 6x IR, Radeon RX 6600 XT (47% uplift)
    "2.3.135": 85.3
    "PR": 125.7
  - name: big mutha truckers, Basic Blending, 6x IR, Radeon RX 6600 XT (~162% uplift)
    "2.3.135": 54.9
    "PR": 144.1
barOptions:
  "2.3.135":
    fillColor: "rgb(106, 156, 255)"
  "PR":
    fillColor: "rgb(200, 45, 69)"
axis:
  x:
    dataKey: name
  y:
    label: "Frames Per Seconds (VPS)"
