version: '3'

tasks:
  new-article:
    cmds:
      - python ./scripts/make-new-article.py
  vendor-deps:
    cmds:
      - python ./scripts/vendor-deps.py
  convert-compat:
    cmds:
      - python ./scripts/coerce-compat-data.py
  cleanup-unused-images:
    cmds:
      - python ./scripts/cleanup-unused-assets.py
