@startuml
participant Github as github
participant "Website Backend" as backend
participant "Website Frontend" as frontend

== A New Release ==

github -> github : New Commit on master
github -> github : Actions Workflow to Build Release
github -> github : Build Release Metadata .yaml file to be bundled with release
activate github
github -> github : Determine auto-incrementing build number
github -> github : Metadata - include commit SHA
alt from-pr? case
    github -> github : Use PR Body as Description
    github -> github : Metadata - include PR number
else was a commit
    github -> github : Use Commit Message as Description
end
github -> github : Bundle .yaml file with release
deactivate github

alt dev-build?
    github -> github : Cut Pre-Release (v1.X.<auto-incrementing number here, if>)
else stable release
    github -> github : Cut Pre-Release (v1.X.Y) where Y is probably 0
end

github -> backend : Fire Webhook that New Release has been Cut
backend -> github : Pool releases API, invalidate cache
frontend -> backend : On Page Load, request current release information
frontend -> frontend : Render Release Page
frontend -> github : Download Release via Github Link
@enduml
