data:
  - name: NFS Carbon, High Blending, 8x IR, 2060 Super (~1060%)
    "1.6.0": 9
    "2.0": 104
  - name: Sly 2, 3x IR, 2070 Super (~166.7%)
    "1.6.0": 67
    "2.0": 178
barOptions:
  "1.6.0":
    fillColor: "rgb(106, 156, 255)"
  "2.0":
    fillColor: "rgb(200, 45, 69)"
axis:
  x:
    dataKey: name
  y:
    label: "Frames Per Seconds (VPS)"
